POST http://localhost:4800/user/register
Content-Type: application/json

{
    "full_name": "annan",
    "email": "annan7@gmail.com",
    "phone_number": "0719904954",
    "password": "123456789"
}

###
POST http://localhost:3800/user/login
Content-Type: application/json

{
     "email": "josh@gmail.com",
    "password": "123456789"
}
