POST http://localhost:4800/user/register
Content-Type: application/json

{
    "full_name": "annan",
    "email": "annan@gmail.com",
    "phone_number": "0798904954",
    "password": "123456789"
}

###
POST http://localhost:4800/user/login

{
     "email": "annan@gmail.com",
    "password": "123456789"
}
